In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Multiple Linear Regression

$y = b_0 + b_1x_1 +b_2x_2 +b_3x_3 + ... +b_nx_n$

#### Building a Model
* All in values
* Backward Elimination
* Forward Selection
* Bidirectional Elimination
* Score Comparison

##### All in values
* You have a prior knowledge
* You have to
* you are going to implement backward elimination


##### Backward elimination
1. Select a significance level to stay in the model ($SL = 0.05$)
2. Fit the full model with all possible predictors
3. Consider the predictor with the highest P-value if  $P > SL$ go to step
4 otherwise go the to finish
4. Remove the predictor (variable)
5. Fit model without the variable (recursively until you reach equilibrium)

##### Forward elimination
1. Select a significance level to stay in the model ($SL = 0.05$)
2. Fit all simple regression models $y ~ x_n$Select the one with the lowest P-value
3. Keep this variable and fill all possible models with one extra predictor added to the ones(s)
 you already have
4. Consider the predictor with the lowest P-value if $P < SL$ to step 3 otherwise to Finish (Keep the previous one)


##### Bidirectional elimination
1. Select a significance level to stay and enter the model ($SLENTER = 0.05$)
($SLSTAY = 0.05$)
2. Perform the next step of forward Selection  ( new variable must have $P<SLENTER$) to enter
3. Perform all the steps of backward Elimination (old variables must have $P<SLSTAY$) to stay
4. No new variables can enter and no variables can exit


##### Possible  elimination
1. Select criterion of goodness of fit
2. Construct All possible Regression models $2^N-1$ combinations
3. Select the one with the best criterion

In [3]:
data_set = pd.read_csv('data_sets/50_Startups.csv')
X = data_set.iloc[:,:-1].values
y = data_set.iloc[:,-1].values

print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

### Encode Categorical data

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3